Recruitment/Recruitment/Controllers/NilaiAptitudeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recruitment.DAL;

namespace Recruitment.Controllers
{
    public class NilaiAptitudeController : Controller
    {
        private RecruitmentDbContext db = new RecruitmentDbContext();

        // GET: NilaiAptitude
        public ActionResult Index()
        {
            return View(db.tbNilaiAptitude.ToList());
        }

        // GET: NilaiAptitude/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiAptitude tbNilaiAptitude = db.tbNilaiAptitude.Find(id);
            if (tbNilaiAptitude == null)
            {
                return HttpNotFound();
            }
            return View(tbNilaiAptitude);
        }

        // GET: NilaiAptitude/Create
        public ActionResult Create()
        {
            try
            {
                if (!string.IsNullOrEmpty(Url.RequestContext.RouteData.Values["id"].ToString()))
                {
                    int id = Convert.ToInt32(Url.RequestContext.RouteData.Values["id"].ToString());
                    ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat.Where(dt => dt.KodeProsesRekrutmen == id), "KodeProsesRekrutmen", "Nama");
                    var vTanggalProsesRekrutmen = db.vProsesRekrutmenKandidat.Where(dt => dt.KodeProsesRekrutmen == id).Select(dt => dt.TanggalProsesRekrutmen).SingleOrDefault();
                    ViewBag.TanggalProsesRekrutmen = vTanggalProsesRekrutmen.ToString();
                    ViewBag.Display = "";
                }
                else
                {
                    ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama");
                    ViewBag.Display = "style=display:none";
                }
            }
            catch (Exception)
            {
                ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama");
                ViewBag.TanggalProsesRekrutmen = DateTime.Now.Date.ToShortDateString();
                ViewBag.Display = "style=display:none";
            }

            return View();
        }

        // POST: NilaiAptitude/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KodeNilaiAptitude,KodeProsesRekrutmen,NilaiAll,NilaiKompleks,NilaiLogika,NilaiPola,Grade,TanggalDibuat,Pengguna")] tbNilaiAptitude tbNilaiAptitude)
        {
            if (ModelState.IsValid)
            {
                tbNilaiAptitude.TanggalDibuat = DateTime.Now.Date;
                tbNilaiAptitude.Pengguna = "Admin";
                db.tbNilaiAptitude.Add(tbNilaiAptitude);
                db.SaveChanges();
                return RedirectToAction("Index", "ProsesRekrutmen");
            }

            return View(tbNilaiAptitude);
        }

        // GET: NilaiAptitude/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiAptitude tbNilaiAptitude = db.tbNilaiAptitude.Find(id);
            if (tbNilaiAptitude == null)
            {
                return HttpNotFound();
            }
            return View(tbNilaiAptitude);
        }

        // POST: NilaiAptitude/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KodeNilaiAptitude,KodeProsesRekrutmen,NilaiAll,NilaiKompleks,NilaiLogika,NilaiPola,Grade,TanggalDibuat,Pengguna")] tbNilaiAptitude tbNilaiAptitude)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbNilaiAptitude).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbNilaiAptitude);
        }

        // GET: NilaiAptitude/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiAptitude tbNilaiAptitude = db.tbNilaiAptitude.Find(id);
            if (tbNilaiAptitude == null)
            {
                return HttpNotFound();
            }
            return View(tbNilaiAptitude);
        }

        // POST: NilaiAptitude/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbNilaiAptitude tbNilaiAptitude = db.tbNilaiAptitude.Find(id);
            db.tbNilaiAptitude.Remove(tbNilaiAptitude);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Recruitment/Recruitment/Controllers/NilaiPsikologiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recruitment.DAL;
using System.ComponentModel.DataAnnotations;

namespace Recruitment.Controllers
{
    public class NilaiPsikologiController : Controller
    {
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime TanggalProsesRekrutmen { get; set; }

        private RecruitmentDbContext db = new RecruitmentDbContext();

        // GET: NilaiPsikologi
        public ActionResult Index()
        {
            var tbNilaiPsikologi = db.tbNilaiPsikologi.Include(t => t.tbProsesRekrutmen);
            return View(tbNilaiPsikologi.ToList());
        }

        // GET: NilaiPsikologi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiPsikologi tbNilaiPsikologi = db.tbNilaiPsikologi.Find(id);
            if (tbNilaiPsikologi == null)
            {
                return HttpNotFound();
            }
            return View(tbNilaiPsikologi);
        }

        // GET: NilaiPsikologi/Create
        public ActionResult Create()
        {
            try
            {
                if (!string.IsNullOrEmpty(Url.RequestContext.RouteData.Values["id"].ToString()))
                {
                    int id = Convert.ToInt32(Url.RequestContext.RouteData.Values["id"].ToString());
                    ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat.Where(dt => dt.KodeProsesRekrutmen == id), "KodeProsesRekrutmen", "Nama");
                    var vTanggalProsesRekrutmen = db.vProsesRekrutmenKandidat.Where(dt => dt.KodeProsesRekrutmen == id).Select(dt => dt.TanggalProsesRekrutmen).SingleOrDefault();
                    ViewBag.TanggalProsesRekrutmen = vTanggalProsesRekrutmen.ToString();
                    ViewBag.Display = "";
                }
                else
                {
                    ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama");
                    ViewBag.Display = "style=display:none";
                }
            }
            catch (Exception)
            {
                ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama");
                ViewBag.TanggalProsesRekrutmen = DateTime.Now.Date.ToShortDateString();
                ViewBag.Display = "style=display:none";
            }

            return View();
        }

        // POST: NilaiPsikologi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KodeNilaiPsikolog,KodeProsesRekrutmen,DeksripsiHasilTest,KesimpulanHasilTest,KodeDokumen")] tbNilaiPsikologi tbNilaiPsikologi)
        {
            if (ModelState.IsValid)
            {
                tbNilaiPsikologi.TanggalDibuat = DateTime.Now.Date;
                tbNilaiPsikologi.Pengguna = "Admin";
                db.tbNilaiPsikologi.Add(tbNilaiPsikologi);
                db.SaveChanges();
                return RedirectToAction("Index", "ProsesRekrutmen");
            }

            ViewBag.KodeProsesRekrutmen = new SelectList(db.tbProsesRekrutmen, "KodeProsesRekrutmen", "Pengguna", tbNilaiPsikologi.KodeProsesRekrutmen);
            return View(tbNilaiPsikologi);
        }

        // GET: NilaiPsikologi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiPsikologi tbNilaiPsikologi = db.tbNilaiPsikologi.Find(id);
            if (tbNilaiPsikologi == null)
            {
                return HttpNotFound();
            }
            //ViewBag.KodeProsesRekrutmen = new SelectList(db.tbProsesRekrutmen, "KodeProsesRekrutmen", "Nama", tbNilaiPsikologi.KodeProsesRekrutmen);
            ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat.Where(tb => tb.KodeProsesRekrutmen == tbNilaiPsikologi.KodeProsesRekrutmen), "KodeProsesRekrutmen", "Nama");
            return View(tbNilaiPsikologi);
        }

        // POST: NilaiPsikologi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KodeNilaiPsikolog,KodeProsesRekrutmen,DeksripsiHasilTest,KesimpulanHasilTest,KodeDokumen")] tbNilaiPsikologi tbNilaiPsikologi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbNilaiPsikologi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KodeProsesRekrutmen = new SelectList(db.tbProsesRekrutmen, "KodeProsesRekrutmen", "Pengguna", tbNilaiPsikologi.KodeProsesRekrutmen);
            return View(tbNilaiPsikologi);
        }

        // GET: NilaiPsikologi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbNilaiPsikologi tbNilaiPsikologi = db.tbNilaiPsikologi.Find(id);
            if (tbNilaiPsikologi == null)
            {
                return HttpNotFound();
            }
            return View(tbNilaiPsikologi);
        }

        // POST: NilaiPsikologi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbNilaiPsikologi tbNilaiPsikologi = db.tbNilaiPsikologi.Find(id);
            db.tbNilaiPsikologi.Remove(tbNilaiPsikologi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Recruitment/Recruitment/Controllers/WawancaraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recruitment.DAL;

namespace Recruitment.Controllers
{
    public class WawancaraController : Controller
    {
        private RecruitmentDbContext db = new RecruitmentDbContext();

        // GET: Wawancara
        public ActionResult Index()
        {
            var tbWawancara = db.tbWawancara.Include(t => t.tbProsesRekrutmen);
            return View(tbWawancara.ToList());
        }

        // GET: Wawancara/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbWawancara tbWawancara = db.tbWawancara.Find(id);
            if (tbWawancara == null)
            {
                return HttpNotFound();
            }
            return View(tbWawancara);
        }

        // GET: Wawancara/Create
        public ActionResult Create()
        {
            ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama");
            return View();
        }

        // POST: Wawancara/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KodeWawancara,KodeProsesRekrutmen,TanggalWawancara,DeskripsiHasilWawancara,KesimpulanWawancara,TanggalDibuat,Pengguna")] tbWawancara tbWawancara)
        {
            if (ModelState.IsValid)
            {
                tbWawancara.TanggalDibuat = DateTime.Now.Date;
                tbWawancara.Pengguna = "Admin";
                db.tbWawancara.Add(tbWawancara);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KodeProsesRekrutmen = new SelectList(db.tbProsesRekrutmen, "KodeProsesRekrutmen", "Pengguna", tbWawancara.KodeProsesRekrutmen);
            return View(tbWawancara);
        }

        // GET: Wawancara/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbWawancara tbWawancara = db.tbWawancara.Find(id);
            if (tbWawancara == null)
            {
                return HttpNotFound();
            }
            ViewBag.KodeProsesRekrutmen = new SelectList(db.vProsesRekrutmenKandidat, "KodeProsesRekrutmen", "Nama", tbWawancara.KodeProsesRekrutmen);
            return View(tbWawancara);
        }

        // POST: Wawancara/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KodeWawancara,KodeProsesRekrutmen,TanggalWawancara,DeskripsiHasilWawancara,KesimpulanWawancara")] tbWawancara tbWawancara)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbWawancara).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KodeProsesRekrutmen = new SelectList(db.tbProsesRekrutmen, "KodeProsesRekrutmen", "Pengguna", tbWawancara.KodeProsesRekrutmen);
            return View(tbWawancara);
        }

        // GET: Wawancara/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbWawancara tbWawancara = db.tbWawancara.Find(id);
            if (tbWawancara == null)
            {
                return HttpNotFound();
            }
            return View(tbWawancara);
        }

        // POST: Wawancara/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbWawancara tbWawancara = db.tbWawancara.Find(id);
            db.tbWawancara.Remove(tbWawancara);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Recruitment/Recruitment/Views/ProsesRekrutmen/Create.cshtml
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@model Recruitment.DAL.tbProsesRekrutmen

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Proses Rekrutmen - Tambah</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class="form-group">
            <label class="control-label col-md-2" for="TanggalProsesRekrutmen">Tanggal Proses Rekrutmen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TanggalProsesRekrutmen, new { htmlAttributes = new { @Value = DateTime.Now.Date.ToShortDateString(), @class = "form-control" }, })
                @Html.ValidationMessageFor(model => model.TanggalProsesRekrutmen, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2" for="TanggalLahir">Tanggal Proses Rekrutmen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TanggalProsesRekrutmen, new { htmlAttributes = new { @value = DateTime.Now.ToString("dd-MM-yyyy"), @class = "form-control date-picker", onkeydown = "return false", onpaste = "return false", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.TanggalProsesRekrutmen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="KodeKandidat">Nama Kandidat</label>
            <div class="col-md-10">
                @Html.DropDownList("KodeKandidat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KodeKandidat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Simpan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Kembali", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var currentDay = new Date();

            $(function () {
                $(".date-picker").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0",
                    dateFormat: 'dd-mm-yy'
                });
            });

            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };
        });

    </script>
    <script src="jquery.disable-autofill.js"></script>
    <script>
        $('input[autofill="off"]').disableAutofill();
    </script>
}

Recruitment/Recruitment/Views/ProsesRekrutmen/Delete.cshtml
@model Recruitment.DAL.tbProsesRekrutmen

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Proses Rekrutmen - Hapus</h3>
<br /><br /><br />
<h5>Apakah Anda Yakin Untuk Menghapus Data Ini??</h5>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tanggal Proses Rekrutmen
        </dt>
        <dd>
            @Convert.ToDateTime(Html.DisplayFor(model => model.TanggalProsesRekrutmen).ToString()).ToString("dd MMMM yyyy")
        </dd>

        <dt>
            Nama Kandidat
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tbKandidat.Nama)
        </dd>

        <dt>
            Status Rekrutmen
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProsesStep)
        </dd>

        <dt>
            Tanggal Dibuat
        </dt>
        <dd>
            @(!string.IsNullOrEmpty(Html.DisplayFor(model => model.TanggalDibuat).ToString()) ? Convert.ToDateTime(Html.DisplayFor(model => model.TanggalDibuat).ToString()).ToString("dd MMMM yyyy HH:mm") : "")
        </dd>

        <dt>
            Pembuat
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pengguna)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Kembali", "Index")
        </div>
    }
</div>

Recruitment/Recruitment/Views/ProsesRekrutmen/Details.cshtml
@model Recruitment.DAL.tbProsesRekrutmen

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Proses Rekrutmen - Detail</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tanggal Proses Rekrutmen
        </dt>
        <dd>
            @(!string.IsNullOrEmpty(Html.DisplayFor(model => model.TanggalProsesRekrutmen).ToString()) ? Convert.ToDateTime(Html.DisplayFor(model => model.TanggalProsesRekrutmen).ToString()).ToString("dd MMMM yyyy HH:mm") : "")
        </dd>

        <dt>
            Nama Kandidat
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tbKandidat.Nama)
        </dd>

        <dt>
            Status Rekrutmen
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProsesStep)
        </dd>

        <dt>
            Tanggal Dibuat
        </dt>
        <dd>
            @(!string.IsNullOrEmpty(Html.DisplayFor(model => model.TanggalDibuat).ToString()) ? Convert.ToDateTime(Html.DisplayFor(model => model.TanggalDibuat).ToString()).ToString("dd MMMM yyyy HH:mm") : "")
        </dd>

        <dt>
            Pembuat
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pengguna)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.KodeProsesRekrutmen }) |
    @Html.ActionLink("Kembali", "Index")
</p>

Recruitment/Recruitment/Views/ProsesRekrutmen/Edit.cshtml
@model Recruitment.DAL.tbProsesRekrutmen

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Proses Rekrutmen - Edit</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.KodeProsesRekrutmen)

        <div class="form-group">
            <label class="control-label col-md-2" for="TanggalProsesRekrutmen">Tanggal Proses Rekrutmen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TanggalProsesRekrutmen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TanggalProsesRekrutmen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="KodeKandidat">Nama Kandidat</label>
            <div class="col-md-10">
                @Html.DropDownList("KodeKandidat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KodeKandidat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ProsesStep">Status Rekrutmen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProsesStep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProsesStep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Simpan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Kembali", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Recruitment/Recruitment/Views/ProsesRekrutmen/Index.cshtml
@model IEnumerable<Recruitment.DAL.tbProsesRekrutmen>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Proses Rekrutmen</h3>

<table class="table">
    <tr>
        <th>
            TANGGAL PROSES REKRUTMEN
        </th>
        <th>
            NAMA KANDIDAT
        </th>
        <th>
            STATUS REKRUTMEN
        </th>
        <th>
            AKSI
        </th>
        <th>
            PENILAIAN
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.TanggalProsesRekrutmen)*@
            @Convert.ToDateTime(item.TanggalProsesRekrutmen).ToString("dd MMMM yyyy")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbKandidat.Nama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProsesStep)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.KodeProsesRekrutmen }) |
            @Html.ActionLink("Detail", "Details", new { id=item.KodeProsesRekrutmen }) |
            @Html.ActionLink("Hapus", "Delete", new { id=item.KodeProsesRekrutmen })
        </td>
        <td>
            <a href="@Url.Action("Create", "NilaiAptitude", new { id = item.KodeProsesRekrutmen })">Aptitude</a> |
            <a href="@Url.Action("Create", "NilaiPseudocode", new { id = item.KodeProsesRekrutmen })">Pseudocode</a> |
            <a href="@Url.Action("Create", "NilaiPsikologi", new { id = item.KodeProsesRekrutmen })">Psikologi</a> |
            <a href="@Url.Action("Create", "Wawancara", new { id = item.KodeProsesRekrutmen })">Wawancara</a>
        </td>
    </tr>
}

</table>

<th>
    <p>@Html.ActionLink("Tambah Data", "Create")</p>
</th>